services:
  php:
    image: php:8.3-fpm
    container_name: symfony_php
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www/html
      - /tmp:/tmp
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    ports:
      - "8000:8000"
    working_dir: /var/www/html
    depends_on:
      - db
    command: sh -c "php -S 0.0.0.0:8000 -t public"

  db:
    image: nouchka/sqlite3
    container_name: sqlite_db
    volumes:
      - ./backend/data:/data

  node:
    image: node:18
    container_name: react_frontend
    working_dir: /usr/src/app
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "3000:3000"
      - "5173:5173"
    stdin_open: true
