nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:5173'] # Adres Twojego frontendu
        allow_credentials: true
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        max_age: 3600
    paths:
        '^/api/': # Ścieżki objęte regułami CORS
            allow_origin: ['http://localhost:5173']
