<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'api_cards_list' => [[], ['_controller' => 'App\\Controller\\CardController::listCards'], [], [['text', '/api/cards']], [], [], []],
    'api_cards_create' => [[], ['_controller' => 'App\\Controller\\CardController::addCard'], [], [['text', '/api/cards']], [], [], []],
    'api_cards_get' => [['id'], ['_controller' => 'App\\Controller\\CardController::getCard'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/cards']], [], [], []],
    'api_cards_update' => [['id'], ['_controller' => 'App\\Controller\\CardController::updateCard'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/cards']], [], [], []],
    'api_cards_delete' => [['id'], ['_controller' => 'App\\Controller\\CardController::deleteCard'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/cards']], [], [], []],
];
