<?php

namespace ContainerYedvHX8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCardControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\CardController' shared autowired service.
     *
     * @return \App\Controller\CardController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/CardController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/CardService.php';
        include_once \dirname(__DIR__, 4).'/src/Service/NotificationService.php';

        $container->services['App\\Controller\\CardController'] = $instance = new \App\Controller\CardController(new \App\Service\CardService(($container->privates['App\\Repository\\CardRepository'] ?? $container->load('getCardRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['validator'] ?? self::getValidatorService($container)), new \App\Service\NotificationService(($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')))));

        $instance->setContainer((new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'router' => ['services', 'router', 'getRouterService', false],
            'request_stack' => ['services', 'request_stack', 'getRequestStackService', false],
            'http_kernel' => ['services', 'http_kernel', 'getHttpKernelService', false],
            'serializer' => ['privates', 'serializer', 'getSerializerService', false],
            'parameter_bag' => ['privates', 'parameter_bag', 'getParameterBagService', false],
        ], [
            'router' => '?',
            'request_stack' => '?',
            'http_kernel' => '?',
            'serializer' => '?',
            'parameter_bag' => '?',
        ]))->withContext('App\\Controller\\CardController', $container));

        return $instance;
    }
}
